# References:
#
# https://blog.argoproj.io/draft-argo-cd-v2-6-release-candidate-ced1853bbfdb
# https://github.com/aeciopires/custom-argocd/pull/1
# https://github.com/argoproj/argo-cd/issues/2531

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
    - resources-finalizer.argocd.argoproj.io
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/projects/
  project: default
  # https://argo-cd.readthedocs.io/en/release-2.6/user-guide/multiple_sources/
  sources:
  - repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.3.3
    helm:
      valueFiles:
      - $values/apps/podinfo/values.yaml
      - $values/apps/podinfo/secrets.yaml
  - repoURL: https://github.com/aeciopires/custom-argocd
    # Branch or tag name
    targetRevision: main
    ref: values
  # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
    syncOptions:
    - CreateNamespace=true
