# https://github.com/argoproj/argo-cd/issues/2531
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    #argocd.argoproj.io/manifest-generate-paths: ..
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/aeciopires/custom-argocd.git
    path: testapp
    targetRevision: main
    helm:
      releaseName: testapp
      valueFiles:
        - values.yaml
        - secrets.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: testapp
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
